### ISSUE TITLE
feature: no function 'about us' (landing page)

### ISSUE THREAD

**Issue by TheDen12** [jovi-isorena/css-capstone-breakthrough#115]
![image](https://user-images.githubusercontent.com/103574027/220555158-0d0f91b7-91fa-4fd0-a98e-1f1a2af26b91.png)

**Comment by Yacoldtt** [comment]
@VenCasanova same page lang, ven. same sa event tsaka calendar

**Comment by jovi-isorena** [comment]
i will merge this change, pero dapat gumawa ng about us section sa landingpage. create new ticket para dun @Yacoldtt
