### ISSUE TITLE
style: word 'grouping' is not fully seen (student user)

### ISSUE THREAD

**Issue by beafayah** [jovi-isorena/css-capstone-breakthrough#117]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/125253166/220650451-8c1f60e1-83f6-47b5-90e5-53afd3fa806a.png">

**Comment by GaroLuis09** [comment]
![image](https://user-images.githubusercontent.com/115927398/220853726-2cdb4dfb-09ae-4eb5-9b07-847482b04d3c.png)
done
