### ISSUE TITLE
style: collapse when pressing view button (sysad user)

### ISSUE THREAD

**Issue by Yacoldtt** [jovi-isorena/css-capstone-breakthrough#133]
![image](https://user-images.githubusercontent.com/116000488/220829961-3ae2b957-3a02-4df2-a18a-428779e334ec.png)

**Comment by niceboc** [comment]
![image](https://user-images.githubusercontent.com/84944782/221868987-bf37cdad-88d9-4c44-8e69-d23842df5eb4.png)
Done!
