### ISSUE TITLE
style: dashboard tab - its empty (teacher)

### ISSUE THREAD

**Issue by emrpx** [jovi-isorena/css-capstone-breakthrough#190]
![image](https://user-images.githubusercontent.com/84944130/220907934-6b276fb0-2e88-4b91-b9c3-661d5d649fce.png)

tanggalin nalang siguro kung walang mailagay

**Comment by niceboc** [comment]
![image](https://user-images.githubusercontent.com/84944782/221117703-f9362783-804c-4910-970c-13a4b5e9f62c.png)
done!
