### ISSUE TITLE
style: make it similar in the students pov

### ISSUE THREAD

**Issue by Yacoldtt** [jovi-isorena/css-capstone-breakthrough#225]
![image](https://user-images.githubusercontent.com/116000488/221169804-35666bb1-7257-4ad7-9a9d-9810c390d4b2.png)
![image](https://user-images.githubusercontent.com/116000488/221169941-30bd35d3-48eb-47de-bd1b-70e57b917486.png)

**Comment by GaroLuis09** [comment]
![image](https://user-images.githubusercontent.com/115927398/221192065-3ce73266-641f-4e0e-980d-30fb39d827f3.png)
