### ISSUE TITLE
style: breadcrumb in assessment (teacher)

### ISSUE THREAD

**Issue by Yacoldtt** [jovi-isorena/css-capstone-breakthrough#226]
![image](https://user-images.githubusercontent.com/116000488/221170301-de4ec01a-4267-40f9-bd85-2d2be85ea60a.png)

**Comment by GaroLuis09** [comment]
![image](https://user-images.githubusercontent.com/115927398/221203606-a6659dcc-6509-4fce-b8ee-06b9863b08f0.png)
