### ISSUE TITLE
style: 'messages' is not fully seen (teacher)

### ISSUE THREAD

**Issue by beafayah** [jovi-isorena/css-capstone-breakthrough#269]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/125253166/221472773-e826c989-83a8-4c68-92ac-646ee7b010d5.png">

**Comment by GaroLuis09** [comment]
![image](https://user-images.githubusercontent.com/115927398/222304057-78824cf4-e529-40a3-b4a8-64b78d841124.png)
done
