### ISSUE TITLE
style: subjects tab, bold the subject code (student)

### ISSUE THREAD

**Issue by emrpx** [jovi-isorena/css-capstone-breakthrough#284]
![image](https://user-images.githubusercontent.com/84944130/221544540-f7f2eabd-5d45-498b-b965-7c236541ed3c.png)

pwede rin ba na kung buong subject name nalang ilagay? 
for example:
<b>Earth and Life Science</b>
SCI7

**Comment by GaroLuis09** [comment]
![image](https://user-images.githubusercontent.com/115927398/222310300-6800766a-dd57-48ea-bc2f-c94a63c3f253.png)
done
