### ISSUE TITLE
bug: time is not real time(student)

### ISSUE THREAD

**Issue by blekxsydaloso** [jovi-isorena/css-capstone-breakthrough#285]
![image](https://user-images.githubusercontent.com/84837750/221545438-c7bf0bd8-6081-4c2c-b18a-706c2d6aefba.png)
6:55pm na po pero 3:27am nakalagay same sa post nung teacher

**Comment by jovi-isorena** [comment]
bug to dahil sa setting ng database natin. naka-GMT+0, dapat naka GMT+8. Ako na bahala dito.
