### ISSUE TITLE
style: 'accounts' is not fully seen (super admin)

### ISSUE THREAD

**Issue by beafayah** [jovi-isorena/css-capstone-breakthrough#307]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/125253166/222051534-87b1124e-66a4-4782-aa56-8521a49a4bf4.png">

**Comment by GaroLuis09** [comment]
![image](https://user-images.githubusercontent.com/115927398/222371687-f9fa59d3-5604-4946-ad1a-ea7d693992b2.png)
done
