### ISSUE TITLE
stlye: image in events is too large(sysad user)

### ISSUE THREAD

**Issue by jovi-isorena** [jovi-isorena/css-capstone-breakthrough#45]
![image](https://user-images.githubusercontent.com/49135614/218463151-4e597992-be20-4573-b225-c5648f162fbe.png)

**Comment by GaroLuis09** [comment]
![image](https://user-images.githubusercontent.com/115927398/219303052-82596e00-7468-47e2-acb4-26202ed38b5c.png)

done
