### ISSUE TITLE
style: picture is too large in subjects tab (student user)

### ISSUE THREAD

**Issue by emrpx** [jovi-isorena/css-capstone-breakthrough#47]
![1](https://user-images.githubusercontent.com/84944130/218472316-0d7b533a-bfa5-4a80-9ab0-6d8d97a29bb2.JPG)

**Comment by GaroLuis09** [comment]
![image](https://user-images.githubusercontent.com/115927398/219304528-4fe01c21-e125-4a38-8739-dc122f82b967.png)

Done
