### ISSUE TITLE
bug: no curriculum ID (Sysad user)

### ISSUE THREAD

**Issue by TheDen12** [jovi-isorena/css-capstone-breakthrough#50]
![image](https://user-images.githubusercontent.com/103574027/218646073-e09c9e88-9616-47a8-971e-a781cbc9f27d.png)

**Comment by Yacoldtt** [comment]
pa linaw @TheDen12

**Comment by jovi-isorena** [comment]
Whole process is being reworked. Issue not relevant anymore.
