### ISSUE TITLE
bug: error in creating badge (Sysad user)

### ISSUE THREAD

**Issue by TheDen12** [jovi-isorena/css-capstone-breakthrough#54]
![image](https://user-images.githubusercontent.com/103574027/218664612-5514a2a2-7e3a-43eb-9ccf-02bf14557603.png)

![image](https://user-images.githubusercontent.com/103574027/218664545-792b99aa-b9e6-4f12-ad30-16e1877a758b.png)

**Comment by Astra0023** [comment]
DONE
