### ISSUE TITLE
style: the welcome banner is very close to the header (student)

### ISSUE THREAD

**Issue by blekxsydaloso** [jovi-isorena/css-capstone-breakthrough#58]
![image](https://user-images.githubusercontent.com/84837750/218746247-4713ca93-c05a-48f7-bce8-6d56df0e8646.png)

**Comment by GaroLuis09** [comment]
![image](https://user-images.githubusercontent.com/115927398/219304717-c630c98b-21e6-4e6e-9423-51fa42f9d12d.png)

Done
