### ISSUE TITLE
style: calendar at the landing page is very large (all users)

### ISSUE THREAD

**Issue by blekxsydaloso** [jovi-isorena/css-capstone-breakthrough#66]
![image](https://user-images.githubusercontent.com/84837750/218753117-b3ab5d3a-5da8-415f-b7e5-ee3858a020ab.png)

**Comment by GaroLuis09** [comment]
![image](https://user-images.githubusercontent.com/115927398/221182866-d6a2d0aa-ce7b-43e3-a57d-8df988b4e709.png)
![image](https://user-images.githubusercontent.com/115927398/221183403-9cbec688-4f67-4a36-8654-31c3da1d205c.png)
done
