### ISSUE TITLE
style: change color or bold the font of the "Subject Code", "Section", "Number of Students", "Number of Online Students" (teacher user)

### ISSUE THREAD

**Issue by emrpx** [jovi-isorena/css-capstone-breakthrough#70]
![image](https://user-images.githubusercontent.com/84944130/218755404-6680b17e-a1ee-450d-b47a-348be3404a60.png)
 
 magulo rin po, di po magets kung ano po ung mga number kung online or number ng students ba

**Comment by niceboc** [comment]
![image](https://user-images.githubusercontent.com/84944782/219400159-234ff436-208a-491b-b1b8-dfa20195f953.png)
Done!
