### ISSUE TITLE
style: message logo is very large (teacher)

### ISSUE THREAD

**Issue by blekxsydaloso** [jovi-isorena/css-capstone-breakthrough#72]
![image](https://user-images.githubusercontent.com/84837750/218757491-dca4a353-d43f-42ac-9b9d-a3d8231af9c3.png)

**Comment by niceboc** [comment]
![image](https://user-images.githubusercontent.com/84944782/219301671-24f98727-2dc6-43e0-a27e-141aa5e750f8.png)
Done!
