### ISSUE TITLE
sytle: send button and message is very close to the nav-side bar (teacher)

### ISSUE THREAD

**Issue by blekxsydaloso** [jovi-isorena/css-capstone-breakthrough#74]
![image](https://user-images.githubusercontent.com/84837750/218757751-f7f222cb-0ef4-4d34-95c7-84d028b8aef5.png)

**Comment by niceboc** [comment]
![image](https://user-images.githubusercontent.com/84944782/219301375-b155f97b-b0b4-43ea-aa6b-e1e934978bfa.png)
Done!
