### ISSUE TITLE
style: the grade level should be "Grade 7" not "7" only (teacher)

### ISSUE THREAD

**Issue by blekxsydaloso** [jovi-isorena/css-capstone-breakthrough#78]
![image](https://user-images.githubusercontent.com/84837750/218758660-7e2805da-a3b0-40df-a079-29b351598f83.png)

**Comment by niceboc** [comment]
![image](https://user-images.githubusercontent.com/84944782/219301088-d7297ccd-cc76-4198-a0a5-c6a95036458f.png)
Done!
