### ISSUE TITLE
style: badge button is too large (teacher)

### ISSUE THREAD

**Issue by blekxsydaloso** [jovi-isorena/css-capstone-breakthrough#80]
![image](https://user-images.githubusercontent.com/84837750/218759873-57e9fedf-160a-4768-a1b8-1d7f313f41c8.png)

**Comment by niceboc** [comment]
![image](https://user-images.githubusercontent.com/84944782/219300443-193ef241-6651-4011-a373-07706a76e869.png)
Done!
