### ISSUE TITLE
bug: can't show time after you saved it (sysad user)

### ISSUE THREAD

**Issue by TheDen12** [jovi-isorena/css-capstone-breakthrough#82]
![image](https://user-images.githubusercontent.com/103574027/218762925-5552a958-55b0-4df9-b8de-857160d17aba.png)
After I clicked the save button

![image](https://user-images.githubusercontent.com/103574027/220550599-b3319dc0-a8dd-44a9-b008-f80930bfe082.png)

**Comment by jovi-isorena** [comment]
done #292
