### ISSUE TITLE
bug: no changing of day after you saved it (Sysad user)

### ISSUE THREAD

**Issue by TheDen12** [jovi-isorena/css-capstone-breakthrough#83]
![image](https://user-images.githubusercontent.com/103574027/218764527-16289af0-1956-4aa8-8448-89c609d589d7.png)
After I click save subj
![image](https://user-images.githubusercontent.com/103574027/220550177-28da4e24-5920-4113-9f84-0ad18f53ec24.png)

**Comment by jovi-isorena** [comment]
done #292
