### ISSUE TITLE
feature: clickable logo no function (sysad user)

### ISSUE THREAD

**Issue by TheDen12** [jovi-isorena/css-capstone-breakthrough#84]
![image](https://user-images.githubusercontent.com/103574027/218764913-56e2fc98-983f-49bc-8773-3660bf29ead2.png)

**Comment by Yacoldtt** [comment]
@TheDen12 anong logo tinutukoy mo?

**Comment by TheDen12** [comment]
eto
![image](https://user-images.githubusercontent.com/103574027/219266155-b758809f-0d8a-4a12-95d9-adb25c6a6b7f.png)
