### ISSUE TITLE
style: alignment of error message (log in page)

### ISSUE THREAD

**Issue by TheDen12** [jovi-isorena/css-capstone-breakthrough#90]
![image](https://user-images.githubusercontent.com/103574027/219266489-cbb6ce31-b5ca-40a8-824c-c15b4ec6aa13.png)

**Comment by Yacoldtt** [comment]
doble na 'to, pre. nailagay na ni blekxsy, #68

**Comment by niceboc** [comment]
![image](https://user-images.githubusercontent.com/84944782/220525658-9c98553b-bafd-4235-8791-218e59b7f361.png)
fixed already, last week
