### ISSUE TITLE
style: class stream link affects message link (student)

### ISSUE THREAD

**Issue by Yacoldtt** [jovi-isorena/css-capstone-breakthrough#96]
![image](https://user-images.githubusercontent.com/116000488/219399151-c09c5224-dd06-4790-b1e2-c6f37e49e2d1.png)

**Comment by GaroLuis09** [comment]
![image](https://user-images.githubusercontent.com/115927398/220848765-caafd2f2-0c2a-4463-ba39-b2150242542d.png)
done
